package co.edu.udistrital.model.enums;

public enum OperationZone {
	USAQUEN, CHAPINERO, SANTA_FE, SAN_CRISTOBAL, USME, TUNJUELITO, BOSA, KENNEDY, FONTIBON, ENGATIVA, SUBA, BARRIOS_UNIDOS, TEUSAQUILLO, LOS_MARTIRES, ANTONIO_NARIÑO, PUENTE_ARANDA, LA_CANDELARIA, RAFAEL_URIBE_URIBE, CIUDAD_BOLIVAR, SUMAPAZ
}
